const voices = [
  { mark: "01", title: "Memória oral", text: "Relatos de quem vive e viveu no Rio da Casca ajudam a reconhecer mudanças, costumes, lugares e acontecimentos que não aparecem nos documentos oficiais." },
  { mark: "02", title: "Fotografias de família", text: "Retratos, festas, trabalhos e paisagens formam um acervo visual capaz de devolver nomes, datas e contexto à história do território." },
  { mark: "03", title: "Saberes do cotidiano", text: "Receitas, cultivos, ofícios e modos de cuidar da terra conectam gerações e mostram como a comunidade constrói sua própria identidade." },
];

const pillars = [
  { mark: "01", title: "Memória", text: "Preservar documentos, fotografias, histórias, nomes e testemunhos que ajudam a reconhecer a trajetória da comunidade.", href: "/acervo", action: "Explorar o acervo" },
  { mark: "02", title: "Água", text: "Conhecer e cuidar do Rio da Casca, de sua nascente, das cachoeiras e das paisagens ligadas ao seu curso.", href: "/territorio", action: "Conhecer o território" },
  { mark: "03", title: "Futuro", text: "Fortalecer a participação responsável, a educação, os projetos e a transmissão desse patrimônio às próximas gerações.", href: "/contribua", action: "Participar do projeto" },
];

export default function Comunidade() {
  return <main>
    <header className="topbar community-topbar"><a className="brand" href="/" aria-label="Rio da Casca — início"><span className="brand-mark">RC</span><span>Rio da Casca<small>memória do território</small></span></a><nav aria-label="Navegação principal"><a href="/historia">História</a><a href="/territorio">Território</a><a className="active" href="/comunidade">Comunidade</a><a href="/acervo">Acervo</a><a href="https://musicas.chapada.ia.br/">Músicas</a></nav><a className="menu-link" href="/contribua">Contribua <span>↗</span></a></header>
    <section className="community-hero"><p className="eyebrow">Pessoas e comunidade · Rio da Casca</p><h1>Um lugar existe<br/><em>em quem o vive.</em></h1><div className="community-hero-note"><span>Arquivo em formação</span><p>Esta página começa pelas práticas coletivas já documentadas. Nomes, retratos e depoimentos serão incluídos somente com contexto e autorização.</p></div></section>
    <section className="community-pillars" aria-labelledby="community-pillars-title"><div className="pillars-intro"><p className="section-index">01 — Eixo comunitário</p><h2 id="community-pillars-title">Memória, <em>água e futuro.</em></h2><p>Três compromissos conectam a história já vivida, o cuidado com o território e a participação das próximas gerações.</p></div><div className="pillar-grid">{pillars.map((pillar) => <a href={pillar.href} key={pillar.mark}><span>{pillar.mark}</span><small>Compromisso</small><h3>{pillar.title}</h3><p>{pillar.text}</p><b>{pillar.action} →</b></a>)}</div></section>
    <section className="network-section community-network-intro"><div className="network-section-head"><p className="section-index">02 — Rede comunitária</p><div><h2>Participar também é preservar.</h2><p>A nova rede aproxima moradores, famílias, pesquisadores, produtores, educadores, jovens e amigos do território em torno de princípios públicos de cuidado e verificação.</p></div></div><div className="network-grid"><a href="/rede-comunitaria"><span>Participação</span><h3>Conheça a rede</h3><p>Veja quem pode participar e os caminhos de colaboração.</p><b>Abrir a rede →</b></a><a href="/diretrizes"><span>Convivência</span><h3>Leia as diretrizes</h3><p>Respeito, consentimento, proteção de dados e transparência.</p><b>Conhecer princípios →</b></a><a href="/audiovisual"><span>Memória viva</span><h3>Famílias, pessoas e vozes</h3><p>Estrutura em formação para entrevistas, fotografias e história oral.</p><b>Ver audiovisual →</b></a></div></section>
    <section className="cascaju"><div className="cascaju-title"><p className="section-index">03 — Tradição compartilhada</p><h2>Festa do<br/>Cascaju.</h2></div><div className="cascaju-copy"><p className="big-copy">Caju, encontro e pertencimento.</p><p>Realizada pela associação da comunidade, a festa reúne cultura popular, gastronomia e integração entre moradores e visitantes. Em 2025, chegou à 22ª edição.</p><p>O caju aparece em doces e sucos e também representa uma fonte de renda para famílias locais, aproximando celebração, produção e economia comunitária.</p><a href="https://www.chapadadosguimaraes.mt.gov.br/Noticias/Chapada-dos-guimaraes-celebra-a-tradicao-e-a-cultura-local-na-22-festa-do-cascaju-2758/" target="_blank" rel="noreferrer">Conhecer a fonte <span>↗</span></a></div></section>
    <section className="community-numbers"><article><strong>22ª</strong><span>edição da Festa do Cascaju em 2025</span></article><article><strong>20+</strong><span>anos de tradição comunitária documentada</span></article><article><strong>05</strong><span>tendas destinadas a apoiar feiras da agricultura familiar</span></article></section>
    <section className="living-archive"><div className="living-heading"><p className="section-index">04 — Acervo vivo</p><h2>O que queremos preservar.</h2></div><div className="voice-list">{voices.map((voice) => <article key={voice.mark}><span>{voice.mark}</span><h3>{voice.title}</h3><p>{voice.text}</p></article>)}</div></section>
    <section className="family-farming"><div><p className="section-index">05 — Trabalho e autonomia</p><h2>Da terra para a comunidade.</h2></div><div><p>A Associação de Moradores e Produtores representa uma dimensão essencial da vida local. Em 2023, recebeu estruturas para apoiar feiras e a comercialização da produção familiar.</p><a href="/acervo/apoio-agricultura-familiar">Abrir registro no acervo <span>→</span></a></div></section>
    <section className="memory-invite"><p className="section-index">Sua história faz parte</p><h2>Ajude a dar nome, voz e rosto a este acervo.</h2><p>Envie uma fotografia, um documento ou um breve relato. Antes de publicar, entraremos em contato para confirmar informações e autorização de uso.</p><a className="button light" href="/contribua">Compartilhar uma memória</a></section>
    <footer><div className="brand footer-brand"><span className="brand-mark">RC</span><span>Rio da Casca<small>memória do território</small></span></div><p>Um acervo comunitário dedicado à história, à natureza e às pessoas do Rio da Casca.</p><div className="footer-meta"><span>Chapada dos Guimarães · MT · Brasil</span><span>© 2026 Rio da Casca</span></div></footer>
  </main>;
}
