const records = [
  { code: "FOT-001", type: "Fotografia", year: "Século XX", title: "Usina Hidrelétrica do Rio da Casca", text: "Registro fotográfico em preto e branco das obras da Usina Rio da Casca III, preservado no acervo dos municípios brasileiros.", source: "IBGE Biblioteca", href: "https://biblioteca.ibge.gov.br/index.php/biblioteca-catalogo?id=441551&view=detalhes" },
  { code: "DOC-001", type: "Documento", year: "1994", title: "Criação da Estação Ecológica", text: "Referência à Lei estadual nº 6.437, que criou a Estação Ecológica do Rio da Casca em dois perímetros de proteção.", source: "Plano Diretor Municipal", href: "https://www.chapadadosguimaraes.mt.gov.br/fotos_documentos_downloads/6067.pdf" },
  { code: "MAP-001", type: "Localização", year: "Atual", title: "Cachoeira do Casca / Martinha", text: "Descrição pública do atrativo, distância desde o centro de Chapada, coordenadas e ligação para localização.", source: "Prefeitura de Chapada", href: "https://www.chapadadosguimaraes.mt.gov.br/Turismo/Atrativos-Turistico/39/" },
  { code: "MAP-002", type: "Localização", year: "Atual", title: "Cachoeira da Pedra Furada", text: "Registro municipal da cachoeira situada na comunidade do Rio da Casca, com orientação geral de acesso e coordenadas.", source: "Prefeitura de Chapada", href: "https://www.chapadadosguimaraes.mt.gov.br/Turismo/Atrativos-Turistico/40/" },
  { code: "EVE-001", type: "Evento", year: "2025", title: "22ª Festa do Cascaju", text: "Registro da celebração organizada pela comunidade, reunindo cultura, gastronomia, economia local e integração.", source: "Prefeitura de Chapada", href: "https://www.chapadadosguimaraes.mt.gov.br/Noticias/Chapada-dos-guimaraes-celebra-a-tradicao-e-a-cultura-local-na-22-festa-do-cascaju-2758/" },
  { code: "COM-001", type: "Comunidade", year: "2023", title: "Apoio à agricultura familiar", text: "Registro da entrega de estruturas para feiras à Associação de Moradores e Produtores da Comunidade Rio da Casca.", source: "Prefeitura de Chapada", href: "https://www.chapadadosguimaraes.mt.gov.br/Noticias/Seaf-mt-entrega-ao-rio-da-casca-05--unidades-de-tendas-de-feira-1946/" },
];

const categories = ["Todos", "Fotografias", "Documentos", "Mapas", "Vídeos", "Relatos"];

export default function Acervo() {
  return <main>
    <header className="topbar archive-topbar"><a className="brand" href="/" aria-label="Rio da Casca — início"><span className="brand-mark">RC</span><span>Rio da Casca<small>memória do território</small></span></a><nav aria-label="Navegação principal"><a href="/historia">História</a><a href="/territorio">Território</a><a href="/comunidade">Comunidade</a><a className="active" href="/acervo">Acervo</a></nav><a className="menu-link" href="/">Voltar ao início <span>↗</span></a></header>

    <section className="archive-hero"><div><p className="eyebrow">Acervo digital · Rio da Casca</p><h1>Guardar para<br/><em>compartilhar.</em></h1></div><div className="archive-intro"><p>Um catálogo em formação para reunir documentos, imagens, mapas e relatos sobre o território.</p><span>Versão inicial · 06 registros públicos</span></div></section>

    <section className="archive-toolbar" aria-label="Categorias do acervo"><p>Explorar por categoria</p><div>{categories.map((category, index) => <span className={index === 0 ? "selected" : ""} key={category}>{category}</span>)}</div><small>Os filtros serão ativados conforme o acervo crescer.</small></section>

    <section className="archive-catalog"><div className="catalog-heading"><p className="section-index">01 — Catálogo inicial</p><h2>Registros de referência.</h2><p>Cada item aponta para a instituição ou órgão que mantém o documento original. O portal não altera o conteúdo das fontes.</p></div><div className="record-list">{records.map((record) => <article key={record.code}><div className="record-meta"><span>{record.code}</span><span>{record.type}</span><span>{record.year}</span></div><div className="record-copy"><h3>{record.title}</h3><p>{record.text}</p></div><a href={record.href} target="_blank" rel="noreferrer"><span>{record.source}</span><b>↗</b></a></article>)}</div></section>

    <section className="archive-method"><div><p className="section-index">02 — Como cuidamos</p><h2>Origem, contexto e respeito.</h2></div><div className="method-list"><article><span>01</span><h3>Identificar</h3><p>Registrar autoria, data, lugar, pessoas e origem sempre que essas informações estiverem disponíveis.</p></article><article><span>02</span><h3>Confirmar</h3><p>Comparar informações e sinalizar claramente aquilo que ainda estiver em pesquisa.</p></article><article><span>03</span><h3>Autorizar</h3><p>Publicar acervos particulares somente com a concordância de quem detém seus direitos.</p></article></div></section>

    <section className="archive-invite"><p className="section-index">Contribua com o acervo</p><h2>Um documento guardado pode revelar uma história inteira.</h2><p>Envie uma descrição do material que você possui. A equipe entrará em contato antes de qualquer publicação.</p><a className="button light" href="mailto:contato@riodacasca.com.br?subject=Contribuição%20para%20o%20Acervo%20Rio%20da%20Casca">Indicar um material</a></section>
    <footer><div className="brand footer-brand"><span className="brand-mark">RC</span><span>Rio da Casca<small>memória do território</small></span></div><p>Um acervo comunitário dedicado à história, à natureza e às pessoas do Rio da Casca.</p><div className="footer-meta"><span>Chapada dos Guimarães · MT · Brasil</span><span>© 2026 Rio da Casca</span></div></footer>
  </main>;
}
